# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'word4' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for word4

#  pod 'WordPress-iOS-Editor'
    pod 'CocoaLumberjack'
    pod 'NSObject-SafeExpectations'

  target 'word4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'word4UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
