# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YCAlertController' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YCAlertController

  pod 'Masonry'

  target 'YCAlertControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YCAlertControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
